### ISSUE TITLE
Mouse click bag

### ISSUE THREAD

**Issue by DekaSKy** [lobomfz/bombcrypto-bot#2]
bot does not connect to metamask, does not list heroes, mouse clicks work uncorrected on windows 10/11, pls help me.

**Comment by lobomfz** [comment]
What's the display resolution? Also make sure to set the browser zoom to 100%

**Comment by DekaSKy** [comment]
> What's the display resolution? Also make sure to set the browser zoom to 100%

1920*1080,yes zoom 100%...original code works...

**Comment by lobomfz** [comment]
The code to get where to click and click it is mostly unchanged, i just reworked the logic. I just had a friend confirm that it works on windows 10 so you need to give me more details. Does it detect where to click? If so, where does it try to click? Do you have more than 1 monitor attached?

**Comment by DekaSKy** [comment]
> Код, по которому можно щелкнуть и щелкнуть, в основном не изменился, я просто переработал логику. Я только что попросил друга подтвердить, что он работает на Windows 10, поэтому вам нужно сообщить мне более подробную информацию. Он определяет, куда нажимать? Если да, то где он пытается щелкнуть? У вас подключено более 1 монитора?

**Comment by DekaSKy** [comment]
> The code to get where to click and click it is mostly unchanged, i just reworked the logic. I just had a friend confirm that it works on windows 10 so you need to give me more details. Does it detect where to click? If so, where does it try to click? Do you have more than 1 monitor attached?
Yea,1 monitor,i can record video.

**Comment by DekaSKy** [comment]
https://user-images.githubusercontent.com/77372383/143005368-cf2f2bed-f121-45ec-ab69-1cb4b5d0bbb2.mp4

https://user-images.githubusercontent.com/77372383/143005394-4e1f0150-e193-4301-9999-bfab22cd85c2.mp4

**Comment by lobomfz** [comment]
I can't see your cursor and your script log, you probably just need to adjust thresholds. Open the script and try higher/lower thresholds on settings that you know are not working, like change `threshold_sign_img = 0.8` to `threshold_sign_img = 0.7`. do some experimenting with that

**Comment by DekaSKy** [comment]
> I can't see your cursor and your script log, you probably just need to adjust thresholds. Open the script and try higher/lower thresholds on settings that you know are not working, like change `threshold_sign_img = 0.8` to `threshold_sign_img = 0.7`. do some experimenting with that


https://user-images.githubusercontent.com/77372383/143197279-0b565f1a-bc6a-45b2-9c65-0a381b48cb0e.mp4

**Comment by lobomfz** [comment]
I adjusted the values of threshold_treasure_hunt which is all you needed to do, this is not a bug on the bot's part, you just need to adjust the thresholds as needed. Also firefox works better than chrome for it. Just do what i said and adjust the thresholds and everything will work.
