### ISSUE TITLE
Dúvida

### ISSUE THREAD

**Issue by THEBESTSZ** [lobomfz/bombcrypto-bot#3]
Oi, tenho uma pequena dúvida, o que "python bcryptobot.py 2>&1 | tee log" faz? Em que parte do código que você captura esses adicionais

**Comment by lobomfz** [comment]
Não é pelo codigo do python em si, mas sim pelo sistema de piping do linux, o "2>&1" redireciona saidas e erros para pipe, o "tee log" mostra os erros na tela do terminal e também redireciona para o arquivo "log",
