### ISSUE TITLE
Olá

### ISSUE THREAD

**Issue by mpcabete** [lobomfz/bombcrypto-bot#4]
Vai ser divertido dar uma lida nas suas commits e ver o que você mudou no codigo original! 
Eu nao sou mto experiente em python e fiz esse bot sem imaginar que outras pessoas leriam o código. Provavelmente tem umas coisas feias no meio do meu código heheeh 
Obrigado por ter disponibilizado sua fork! Quando tiver um tempinho vou ver com calma as mudanças que você fez!

**Comment by lobomfz** [comment]
Opa, primeiramente obrigado pelo trabalho, então, tava precisando de um bot pra varias instancias do jogo, e o seu estava dando muitos problemas que não sabia como arrumar pq sou péssimo em entender código dos outros. As unicas partes 100% reaproveitadas são as funções de pegar as coordenadas e clicar no botão, fora uma parte ou outra, a lógica em si do codigo foi totalmente re-escrita, ta longe de ser perfeita, mas está funcionando bem consistentemente. Se fosse algo menor tinha até feito um pull request mas nesse nivel achei melhor uma fork mesmo. Valeu, qualquer coisa pode me chamar no discord lobo#1125.

Vou fechar o issue pra poder manter clean mas pode falar por aqui também que eu vejo.
